### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by coderGtm** [philipperemy/easy-encryption#13]
The encode function works fine for English as far as I have tested. But it breaks for other Languages. For example, I used the encode function to encode a string in Gujarati. Decoding it produces some weird output. If all languages can not be supported, then can there be a check to ignore unidentified characters and keep them as it is in encoding and decoding?

**Comment by coderGtm** [comment]
Can you please explain how is ot solved? I tried to read the code but there are to many additions so ain't able to figure out. Also I am a beginner.
_Thanks_

**Comment by philipperemy** [comment]
@coderGtm no problem.

I changed the base64 encode and decode functions. 

Those functions could not deal with non english characters.

New functions are: 

https://github.com/philipperemy/easy-encryption/blob/master/Base64.cpp#L42

Old functions were: 

https://github.com/philipperemy/easy-encryption/blob/300e54e67795ddc84a9c72415a196fd7e2476721/b64.h#L9.
